### ISSUE TITLE
[Request]: Publish blogs-campaign-pages

### ISSUE THREAD

**Issue by tneeleygsa** [GSA/US-performance-reporting#100]
### Contact Details

thomas.neeley@gsa.gov

### Request

Made updates to 18 old blog posts to link from them back to the new static campaign pages (#GovLove, #GovPossible, and #FedFashionWeek). Branch: blogs-campaign-pages. No hard deadline to get done, but please publish when you have a chance!

### Refine request (Optional)

As a [TYPE OF USER], I want TO [ACTION], so that I can [ACHIEVE GOAL]. Given I am on [WEBPAGE], When I [ACTION], Then [RESULT].

### How important is this to you?

Nice-to-have

**Comment by metzgr** [comment]
@tneeleygsa Tom, this is done! Thanks so much for putting in this request - much eaiser to track this way
