### ISSUE TITLE
Update CX EO page

### ISSUE THREAD

**Issue by metzgr** [GSA/US-performance-reporting#82]
Given I am on https://www.performance.gov/cx/executive-order/
When I scroll
Then I see the changes Amira requested

### Adapt topper layout from CX HISPs

- [x] Reuse layout from "above the fold" section from CX HISPs (contained in the HTML tags in the image)
- [x] Set hero image to Biden signing EO
- [x] Set title
- [ ] Set first item in Table of Contents

![Image](https://user-images.githubusercontent.com/18745563/220429436-f1206fc5-7102-4418-b8a3-1af48a98fb13.jpg)

### Accordions
- [ ] In each accordion, add new content from Word doc

### Modify "What the American people should expect of their government"
- [ ] Delete stats content from (we just want to preserve the checklist)

**Comment by metzgr** [comment]
See email from Amira for content changes: Updated >https://www.performance.gov/cx/executive-order/

**Comment by metzgr** [comment]
@ryanwoldatwork Let me know if you have bandwidth to tackle first

**Comment by ryanwoldatwork** [comment]
started here: https://github.com/GSA/InterimPerformance-Dot-Gov-2018/pull/2164
