### ISSUE TITLE
Fix broken links on old CX project pages

### ISSUE THREAD

**Issue by metzgr** [GSA/US-performance-reporting#94]
Given I am on an old CX project page (e.g., https://www.performance.gov/cx/projects/facing-a-financial-shock/)
When I click Download the Project Charter PDF
Then I the correct PDF appears

**Comment by metzgr** [comment]
@ryanwoldatwork the download-charter links on the old CX pages are broken and lead to 404 errors. Not sure why - the files they're referencing appear to be in the right folder? I know these pages are populated by underlying data, so thinking you can solve the fastest. Let me know if you have any questions! FYI Aaron asked about this

**Comment by ryanwoldatwork** [comment]
what URL?

**Comment by ryanwoldatwork** [comment]
those files were move to S3.

i fixed them here: https://github.com/GSA/InterimPerformance-Dot-Gov-2018/commit/79fbb86eb569c2f73de0c4696dd69a66d0655330
